before_script:
  - python --version
  - pip install -r requirements.txt

stages:
  - Static Analysis
  - Test

pylint:
  stage: Static Analysis
  script:
  - pylint -d C0301 src/start.py

pytest:
  stage: Test
  script:
  - cd test/;pytest -v